version=1.2.0
group=com.queso.niche
java_version=25

minecraft_version=26.2
mod_name=Modular Muskets
mod_author=Queso
mod_id=niche
license=CC0-1.0
credits=Queso
description=Modular Muskets adds craftable, mix-and-match muskets. Build your barrel, stock, and bracing at a Musket Station, then aim down sights and fire.
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3

neoforge_version=26.2.0.1-beta
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
